New panel plugin to create "CDF" graphs
grafana/grafana-plugin-repository pull request #959
Opened 2021-05-27 12:21 UTC by sebastiangunreben

Hello Grafana cummunity,

I created a panel plugin to visualize the cumulative distribution function of a certain value.
I would be happy to receive your review.

BR,
Sebastian

2021-05-27 13:23 UTC, marcusolsson commented
Awesome! The URL in the pull request needs to reference a zip archive containing your plugin. Could you also run that through the [plugin validator](http://plugin-validator.grafana.net/) to make sure it's ready for review?

2021-05-27 17:40 UTC, sebastiangunreben commented
@marcusolsson … the plugin has already been validated throughout the plugin validator. Do you miss anything before the review process could start?

2021-07-06 16:39 UTC, marcusolsson commented
I've tested the panel and successfully got it working. The only issue I found was that when I clicked "Show thresholds" with the following error:

<img width="561" alt="Screenshot 2021-07-06 at 18 33 37@2x" src="https://user-images.githubusercontent.com/8396880/124636329-b778d500-de88-11eb-8c1d-cc37919b5743.png">

I'm running Grafana 8.0.4 on macOS 11.2.3 with Firefox 89.

I've also configured a Community signature level for `sebastiangunreben-cdf-panel` so you should be able to sign the plugin and update your pull request.

2021-07-07 12:49 UTC, marcusolsson commented
I'm getting an error that the plugin has a Modified signature due to `img/logo.svg` which is not included in the manifest. Any file added to the plugin after it's been signed will cause an error.

Also, could you update the pull request to only include the version you intend to publish. The currently listed versions are not valid plugin packages and won't be published, so you can go ahead and remove them from the list. Thank you! 🙏

2021-07-07 13:28 UTC, marcusolsson requested changes
I've done a final review of the plugin and it all looks good! Just a few fixes in the PR and I'll publish this right away!

2021-07-07 13:28 UTC, marcusolsson commented on repo.json
> +
Could you remove this line?

2021-07-07 13:28 UTC, marcusolsson commented on repo.json
> +      "id": "sebastiangunreben-cdf-plugin",
```suggestion
      "id": "sebastiangunreben-cdf-panel",
```

2021-07-07 13:28 UTC, marcusolsson commented on repo.json
> +      "type": "app",
```suggestion
      "type": "panel",
```

2021-07-07 13:34 UTC, sebastiangunreben commented
I updated pull request (instead of resolving requests via web). Hope that led to the same effect.

2021-07-07 13:44 UTC, merged

2021-07-07 13:45 UTC, marcusolsson commented
Wonderful! I've published the plugin, but please allow a few minutes before it becomes available on grafana.com. 

Thanks for contributing your plugin to the Grafana community! 💪 🙏

2021-07-08 07:14 UTC, sebastiangunreben commented
Great! Thank you very much!